### ISSUE TITLE
Test fails on junit-jupiter-engine 5.4.2

### ISSUE THREAD

**Issue by reebr** [TestFX/TestFX#661]
## Expected Behavior

I'm using the 5.3.1 version of `junit-jupiter-engine` and I would like to bump it to 5.4.2.
The tests work fine on 5.3.1, but fails on 5.4.2.

## Actual Behavior

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
jun 11, 2019 9:47:07 AM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'junit-jupiter' failed to discover tests
java.lang.NoClassDefFoundError: org/junit/jupiter/api/MethodOrdererContext
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.createJavaElementsResolver(DiscoverySelectorResolver.java:86)
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolve(DiscoverySelectorResolver.java:57)
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:50)
	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:168)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:155)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:120)
	at org.apache.maven.surefire.junitplatform.TestPlanScannerFilter.accept(TestPlanScannerFilter.java:56)
	at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:102)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.scanClasspath(JUnitPlatformProvider.java:143)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.ClassNotFoundException: org.junit.jupiter.api.MethodOrdererContext
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 15 more

jun 11, 2019 9:47:07 AM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'junit-jupiter' failed to discover tests
java.lang.NoClassDefFoundError: org/junit/jupiter/api/MethodOrdererContext
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.createJavaElementsResolver(DiscoverySelectorResolver.java:86)
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolve(DiscoverySelectorResolver.java:57)
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:50)
	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:168)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:155)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.ClassNotFoundException: org.junit.jupiter.api.MethodOrdererContext
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 13 more

Results:

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 8.221 s
Finished at: 2019-06-11T09:47:08-03:00
Final Memory: 8M/34M
```

The unique change I've made:

```diff
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter</artifactId>
    <version>5.4.2</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-engine</artifactId>
-    <version>5.3.1</version>
+   <version>5.4.2</version>
    <scope>test</scope>
</dependency>
```

## Specifications

  - Version: JDK 12, JavaFX 12
  - Platform: Windows 10 x64

**Comment by brcolow** [comment]
Interesting. Is MethodOrdererContext used by `testfx-junit5` code? I don't see it from a quick glance and the stack trace looks foreign. Investigatory assistance appreciated.

**Comment by pbauerochse** [comment]
@brcolow @reebr just had the same issue. my problem was, that the `junit-jupiter-api` dependency was included twice: version 5.4.2 from my application pom.xml but testfx also includes the `junit-jupiter-api` as dependency but in version 5.3.1

After adding the exclusion to my pom the tests are working again:

```
<dependency>
    <groupId>org.testfx</groupId>
    <artifactId>testfx-junit5</artifactId>
    <version>${testfx.version}</version>
    <scope>test</scope>
    <exclusions>
        <exclusion>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
        </exclusion>
    </exclusions>
</dependency>```

**Comment by brcolow** [comment]
@pbauerochse Should we (TestFX) not be including that dependency?

**Comment by pbauerochse** [comment]
Good question. I'd say it is up to you to decide that. As most of the times, there is pros and cons to either way: 

if you decide to include the dependency as compile dependency, the user only has to include the test-fx dependency and most propably is good to go. On the other hand you might get the version clashes if you already have the junit dependency included in a different version. The workaround for that would be to exclude the dependency as shown in my previous comment.

If you would set external dependencies to `provided` the user must take care of including the dependencies himself but then is free to choose the proper version he / she desires. But from the point of usability it might confuse users, that are not too familiar with dependency management tools like maven or gradle.

A compromise might be to not have the version number fixed in the dependecies but to use variables, that the user might override. I think spring is using this in their spring boot dependencies.

So instead of

```
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-api</artifactId>
    <version>5.3.1</version>
    <scope>compile</scope>
</dependency>
```
you could do
```
<properties>
    <junit-jupiter.version>5.3.1</junit-jupiter.version>
</properties>

<dependencies>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <version>${junit-jupiter.version}</version>
      <scope>compile</scope>
    </dependency>
</dependencies>
```

so I, as a user, could override that setting:

```
<properties>
    <testfx.version>4.0.15-alpha</testfx.version>
    <junit-jupiter.version>5.4.2</junit-jupiter.version>
</properties>

<dependencies>
    <dependency>
        <groupId>org.testfx</groupId>
        <artifactId>testfx-junit5</artifactId>
        <version>${testfx.version}</version>
    </dependency>
</dependencies>
```

**Comment by reebr** [comment]
> 
> 
> @brcolow @reebr just had the same issue. my problem was, that the `junit-jupiter-api` dependency was included twice: version 5.4.2 from my application pom.xml but testfx also includes the `junit-jupiter-api` as dependency but in version 5.3.1
> 
> After adding the exclusion to my pom the tests are working again:
> 
> ```
> <dependency>
>     <groupId>org.testfx</groupId>
>     <artifactId>testfx-junit5</artifactId>
>     <version>${testfx.version}</version>
>     <scope>test</scope>
>     <exclusions>
>         <exclusion>
>             <groupId>org.junit.jupiter</groupId>
>             <artifactId>junit-jupiter-api</artifactId>
>         </exclusion>
>     </exclusions>
> </dependency>
> ```

Thank U, it worked.

**Comment by brcolow** [comment]
I think that we should make junit-jupiter-api a `provided` dependency. So the user will have to manually include the dependency.
